# Docker-compose provided by Mickael "PAPAMICA" Asseline
# Update : 10/05/2022

#& type: 3
#& title: Grafana
#& description: From heatmaps to histograms, graphs to geomaps: fast and furious visualizations any way you want.
#& note: Website: <a href='https://grafana.com/grafana/dashboards/' target='_blank' rel='noopener'>Grafana.com</a>
#& categories: SelfHosted, Monitoring, PAPAMICA
#& platform: linux
#& logo: https://seeklogo.com/images/G/grafana-logo-15BA0AFA8A-seeklogo.com.png

#% SERVICE: Name of the service (No spaces or points)
#% DATA_LOCATION: Data localization (Example: /apps/service)
#% PLUGINS: Plugins to install (Example: alexanderzobnin-zabbix-app,grafana-singlestat-panel)
#% URL: Service link (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy)

# Work with Portainer
version: "2"
services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    container_name: $SERVICE
    volumes: 
      - $DATA_LOCATION/config:/etc/grafana
      - $DATA_LOCATION/data:/var/lib/grafana
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_SERVER_DOMAIN=$URL
      - GF_SERVER_ROOT_URL=https://$URL
      - GF_INSTALL_PLUGINS=$PLUGINS
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=$PLUGINS
    healthcheck:
      test: wget -nv -t1 --spider 'http://localhost:3000/'
      interval: 1m
      timeout: 30s
      retries: 3
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=3000"
      - "traefik.docker.network=$NETWORK"
      
networks:
  default:
    external:
      name: $NETWORK