# Docker-compose provided by Mickael "PAPAMICA" Asseline
# Update: 10/05/2022

#& type: 3
#& title: FileBrowser
#& description: File manager with web interface
#& note: Website: <a href='https://github.com/filebrowser/filebrowser' target='_blank' rel='noopener'>Github.com</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://avatars.githubusercontent.com/u/35781395?s=200&v=4

#% SERVICE: Name of the service (No spaces or points)
#% DATA_LOCATION: Data localization (Example: /apps/service)
#% FOLDER: Folder of yours files (Example: /data/movies)
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy)

# Work with Portainer
version: "2"

services:
  # FileBrowser : https://github.com/filebrowser/filebrowser
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: $SERVICE
    restart: always
    volumes:
      - $FOLDER:/srv
      - $DATA_LOCATION/config.json:/config.json
      - $DATA_LOCATION/database.db:/database.db
    healthcheck:
      test: wget -nv -t1 --spider 'http://localhost:80'
      interval: 1m
      timeout: 30s
      retries: 3
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"
  
networks:
  default:
    external:
      name: $NETWORK