# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-06-16

#& type: 3
#& title: Home Assistant
#& description: Open source home automation that puts local control and privacy first.
#& note: Website: <a href='https://www.home-assistant.io/' target='_blank' rel='noopener'>Home-Assistant.io</a></br></br>Warning: network mode host used ! </br>Accessible with port: <code>8123</code>
#& categories: SelfHosted, Domotic, PAPAMICA
#& platform: linux
#& logo: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/1200px-Home_Assistant_Logo.svg.png

#% SERVICE: Name of the service (No spaces or points) [home-assistant]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]

# Work with Portainer
version: "2"
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: always
    container_name: $SERVICE
    volumes:
      - $DATA_LOCATION/$SERVICE/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
    healthcheck:
      test: wget -nv -t1 --spider 'http://localhost:8123/'
      interval: 1m
      timeout: 30s
      retries: 3
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater