# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-17

#& type: 3
#& title: Overseerr
#& description: Overseerr is a request management and media discovery tool built to work with your existing Plex ecosystem.
#& note: Website: <a href='https://overseerr.dev/' target='_blank' rel='noopener'>Overseerr.dev</a>
#& categories: SelfHosted, Mediacenter, PAPAMICA
#& platform: linux
#& logo: https://img.papamica.com/logo/overseer.png

#% SERVICE: Name of the service (No spaces or points) [overseerr]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% TZ: Time zone (Exemple: Europe/Paris) [Europe/Paris]


# Work with Portainer
services:
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: $SERVICE
    restart: always
    volumes:
      - $DATA_LOCATION/$SERVICE/config:/config
    environment:
      - TZ=$TZ
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: wget -nv -t1 --spider "http://localhost:5055"
      interval: 1m
      timeout: 30s
      retries: 3
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=5055"
      - "traefik.docker.network=$NETWORK"
    networks:
      - default
networks:
  default:
    external:
      name: $NETWORK