# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-17

#& type: 3
#& title: Prowlarr
#& description: Indexer for torrents and usenets.
#& note: Website: <a href='https://github.com/Prowlarr/Prowlarr' target='_blank' rel='noopener'>Gitub.com</a>
#& categories: SelfHosted, Mediacenter, PAPAMICA
#& platform: linux
#& logo: https://prowlarr.com/logo/256.png

#% SERVICE: Name of the service (No spaces or points) [prowlarr]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% TZ: Time zone (Exemple: Europe/Paris) [Europe/Paris]


# Work with Portainer
services:
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: $SERVICE
    restart: always
    volumes:
      - $DATA_LOCATION/$SERVICE/config:/config
    environment:
      - TZ=$TZ
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: curl --connect-timeout 15 --max-time 100 --silent --show-error --fail "http://localhost:9696" > /dev/null
      interval: 1m
      timeout: 30s
      retries: 3
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.http.services.$SERVICE.loadbalancer.server.port=9696"
      - "traefik.docker.network=$NETWORK"
    networks:
      - default
networks:
  default:
    external:
      name: $NETWORK