# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-12

#& type: 3
#& title: TS-Website
#& description: Web interface for your TeamSpeak
#& note: Website: <a href='https://github.com/Wruczek/ts-website' target='_blank' rel='noopener'>Github.com</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://tsweb.papamica.com/img/icons/defaulticon-64.png

#% SERVICE: Name of the service (No spaces or points) [ts3viewer]
#% DATA_LOCATION: Data localization (Example: /apps/service) [/_data/apps]
#% URL: Service URL (Example: service.papamica.fr or service.com)
#% NETWORK: Your Traefik network (Example: proxy) [proxy]
#% DB_USER: Database user (No spaces or points) [ts3viewer]
#% DB_PASSWORD: Database user password
#% DB_ROOT: Database root password

# Work with Portainer
version: "2"

services:
  tsweb:
    image: yeahnice1/ts-website:latest
    container_name: $SERVICE
    volumes:
      - $DATA_LOCATION/$SERVICE/config:/var/www/html
    restart: always
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"
      
  
  tsweb-db:
    image: mariadb:10.4.12
    container_name: $SERVICE-db
    restart: always
    volumes:
      - $DATA_LOCATION/$SERVICE/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT
      - MYSQL_DATABASE=tsweb
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater

networks:
  default:
    external:
      name: $NETWORK