# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-11

#& type: 3
#& title: VSCode Online
#& description: Web interface for VSCode
#& note: Website: <a href='https://github.com/coder/code-server' target='_blank' rel='noopener'>Github.com</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png

#% SERVICE: name of the service (No spaces or points) [vscode]
#% DATA_LOCATION: data localization (Example: /apps/service) [/_data/apps]
#% URL: service URL (Example: service.papamica.fr or service.com)
#% NETWORK: your Traefik network (Example: proxy) [proxy]
#% PASSWORD: Password to acces web interface

# Work with Portainer
version: "2"

services:
  postgres:
    container_name: $SERVICE
    image: codercom/code-server:latest
    volumes:
      - $DATA_LOCATION/$SERVICE/project:/home/coder/project
    restart: always
    environment:
      - PASSWORD=$PASSWORD
    networks:
      - default
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"

networks:
  default:
    external:
      name: $NETWORK