# Maintainer: Mickael "PAPAMICA" Asseline
# Update: 2022-05-10

#& type: 3
#& title: Website HTML PHP
#& description: Simple HTML website under PHP 7.4
#& note: Website: <a href='https://github.com/LavoWeb/Docker' target='_blank' rel='noopener'>Github.com</a>
#& categories: SelfHosted, PAPAMICA
#& platform: linux
#& logo: http://assets.stickpng.com/thumbs/5847f5bdcef1014c0b5e489c.png

#% SERVICE: name of the service (No spaces or points) [website]
#% DATA_LOCATION: data localization (Example: /apps/service) [/_data/apps]
#% URL: service URL (Example: service.papamica.fr or service.com)
#% NETWORK: your Traefik network (Example: proxy) [proxy]

# Work with Portainer
version: "2"
services:
  web:
    image: lavoweb/php-7.3:latest
    container_name: $SERVICE
    volumes:
      - $DATA_LOCATION/$SERVICE/html:/var/www/html
    restart: always
    networks:
      - default
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    labels:
      - "autoupdate=monitor" # https://github.com/PAPAMICA/container-updater
      - "traefik.enable=true"
      - "traefik.http.routers.$SERVICE.entrypoints=https"
      - "traefik.http.routers.$SERVICE.rule=Host(`$URL`)"
      - "traefik.http.routers.$SERVICE.tls=true"
      - "traefik.http.routers.$SERVICE.tls.certresolver=http"
      - "traefik.docker.network=$NETWORK"
networks:
  default:
    external:
      name: $NETWORK