# Maintainer: Mickael "PAPAMICA" Asseline
# Docker-compose provided by Mickael "PAPAMICA" Asseline
# Last update : 04/09/2021
# Environment variables to declare :
#     - SERVICE : name of the service (example : zabbix-proxy)
#     - HOSTNAME : name of zabbix proxy (example : zabbix-proxy)
#     - ZABBIX_SERVER : FQDN of zabbix server (example : zabbic.domain.tld)
#     - TLSPSKIDENTITY : ID of psk in zabbix server (example : PSK001)
#     - TLSPSKFILE : PSK file  (example : zabbix_agentd.psk)
#     - URL_LOKI : loki service URL (example : http://ip:3100/loki/api/v1/push)
#     - DATA_LOCATION : location of service configuration data (example /app/"service")
#     - NETWORK_APP : application network name
# Work with Portainer
version: '2'
services:
  zabbix-proxy:  
    image: zabbix/zabbix-proxy-sqlite3:ubuntu-5.4-latest
    restart: unless-stopped
    container_name: $SERVICE
    environment:
      ZBX_PROXYMODE: 0
      ZBX_HOSTNAME: $PROXY_HOSTNAME
      ZBX_SERVER_HOST: $ZABBIX_SERVER
      ZBX_ENABLEREMOTECOMMANDS: 1
      ZBX_STARTPOLLERS: 5
      ZBX_IPMIPOLLERS: 1
      ZBX_STARTPOLLERSUNREACHABLE: 1
      ZBX_STARTTRAPPERS: 5
      ZBX_STARTPINGERS: 1
      ZBX_STARTDISCOVERERS: 1
      ZBX_STARTHTTPPOLLERS: 1
      ZBX_STARTVMWARECOLLECTORS: 10
      ZBX_TLSCONNECT: psk
      ZBX_TLSACCEPT: psk
      ZBX_TLSPSKIDENTITY: $TLSPSKIDENTITY
      ZBX_TLSPSKFILE: $TLSPSKFILE
      ZBX_VMWAREFREQUENCY: 60
      ZBX_VMWAREPERFFREQUENCY: 60
      ZBX_VMWARECACHESIZE: 8M
      ZBX_VMWARETIMEOUT: 10
    healthcheck:
      test: grep -qr "zabbix_proxy" /proc/*/status || exit 1
      interval: 1m
      timeout: 30s
      retries: 3
    logging:
      driver: loki
      options:
        loki-url: "$URL_LOKI"
        loki-external-labels: service={{.Name}}
    volumes:
      - $DATA_LOCATION/enc:/var/lib/zabbix/enc
    ports:
      - 10051:10051
    networks: 
      - proxy
networks:
  proxy:
    external:
      name: proxy
